# Generated by Django 2.0.9 on 2019-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='public_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
